### PR TITLE
Add rubocop, enable pry on dev/test

### PR DESCRIPTION
**Pull request by hennevogel**

### CODE REVIEW

**Comment by hennevogel** [comment]
@cornelius the test failure is beyond me. Can you make sense of it?

**Comment by cornelius** [comment]
@hennevogel looks like it couldn't delete the symlink. Not sure how this could happen. I can't reproduce this failure locally.

**Comment by hennevogel** [comment]
@cornelius something with the `Pathname` + `File` combination it seems

**Comment by hennevogel** [comment]
@cornelius or rather `File.exist?` vs `File.lsat`...

**Pull request merged**
